import React from "react";
import Head from "next/head";
import { PublicNav } from "@/navigations/PublicNav";
import MainFooter from "@/navigations/MainFooter";

const PublicLayout = ({ children }) => {
    return (
        <>
            <Head>
                {/* TODO: ajustar los metas de cada pagina del SEO */}
                <title>Remote Squid Web</title>
                <meta
                    name="description"
                    content="Generated by create next app"
                />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className="bg-white min-h-screen min-w-screen">
                <PublicNav />
                {children}
                <MainFooter />
            </div>
        </>
    );
};

export default PublicLayout;
